### ISSUE TITLE
Twentyfifteen theme doesn't use system.yaml dateformat for blog posts

### ISSUE THREAD

**Issue by markosu** [getgrav/grav-skeleton-twentyfifteen-site#1]
Twentyfifteen theme doesn't use system.yaml dateformat in blog items.
It use theme's languages.yaml file for month name.
For Finnish site I would be nice to have support for d.m.Y H:i.

![screenshot 35](https://cloud.githubusercontent.com/assets/6770959/10877812/1593061e-8152-11e5-9bb0-39c8fb40bcf9.png)

**Comment by hexplor** [comment]
Hello markosu,
We made it that way to support multilanguage correctly. Date line is located in 
templates/partials/blog_item.html.twig, line 70
```
<time class="entry-date published updated" datetime="{{ page.date|date('Y-m-d') }}">{{ 'MONTHS_OF_THE_YEAR'|ta(page.date|date('n') - 1) }} {{ page.date|date("d, Y") }}</time> 
```
You can modify it the way you want :)

**Comment by markosu** [comment]
But only way to change dateformat is to custom date line in templates/partials/blog_item.html.twig, line 70 ?

I have in system.yaml but it doesn't work.
```
  dateformat:
    default: 'd.m.Y H:i'
    short: 'd.m.y H:i'
    long: 'd.m.y H:i'
  publish_dates: true
```

So I changed it this way:
```
            <time class="entry-date published updated" datetime="{{ page.date|date('d.m.Y') }}">{{ page.date|date("d.m.Y") }}</time>
```
Then I get right timeformat:

![screenshot 37](https://cloud.githubusercontent.com/assets/6770959/10881742/28e8d29a-816e-11e5-8bf1-ee3fa25d921a.png)

**Comment by hexplor** [comment]
I see what you mean now :) I will fix that :) thanks
